### ISSUE TITLE
Can you add two features, authentication and multi-turn dialogue?

### ISSUE THREAD

**Issue by bravekingzhang** [e-roy/gemini-pro-vision-playground#6]
The Gemini Pro model supports multi-turn dialogue, and I hope to add this feature.

Authentication is to prevent abuse, simply adding password verification.

**Comment by e-roy** [comment]
I do have a multi-turn setup currently for Gemini Pro.  It's using the entire conversation from the state in the frontend passed into `model.generateContentStream`.  I'm not using the `model.startChat` method because it would I wanted to implement the `ai` library to handle communication between front and back.  I still need to explore both methods more on which performs better, currently keeping conversation state in the frontend for this build seems like a better approach.

The gemini-pro-vision doesn't support multi-turn yet that I'm aware of.  If and when it does I will add it here.

For authentication I would suggest using `next-auth` [https://next-auth.js.org/](https://next-auth.js.org/)

I don't plan on adding auth to this repo, I want to make it easy for anyone to start up this repo locally and get started using these models.

@bravekingzhang be sure to update your fork, I've added a lot of changes and fixes since you forked 😄

**Comment by bravekingzhang** [comment]
thanks for your reply
